### ISSUE TITLE
Image cropping error

### ISSUE THREAD

**Issue by swise23** [bizbudding/maitheme-engine#2]
![image](https://cloud.githubusercontent.com/assets/22770965/25863190/d7ff10a6-34b8-11e7-8907-9888e32c4044.png)

**Comment by JiveDig** [comment]
Steps to recreate?

**Comment by swise23** [comment]
ttempted adding an image from the media library as a site logo via Customizer > Site Identity

**Comment by JiveDig** [comment]
It looks like you didn't highlight an area to crop?

**Comment by swise23** [comment]
There doesn't seem to be a way to do so? No grab handles at the corners, click and drag doesn't do it....

**Comment by JiveDig** [comment]
Now has a 'suggested' size, which is kind of annoying cause any aspect ratio works, but at least the cropper is available now.
