### ISSUE TITLE
grid breaks on product when there is an image_bg and show_add_to_cart="true"

### ISSUE THREAD

**Issue by christiebizbudding** [bizbudding/maitheme-engine#5]
[grid content="product" number="6" image_bg="true" show_price="true" show_add_to_cart="true" align="center"]

![screen shot 2017-05-16 at 3 16 33 pm](https://cloud.githubusercontent.com/assets/25107329/26123923/aef15362-3a4a-11e7-88f8-f5cb36fcb521.png)

**Comment by JiveDig** [comment]
ref https://github.com/bizbudding/maitheme/issues/78

**Comment by JiveDig** [comment]
<img width="896" alt="screen shot 2017-05-16 at 9 39 12 pm" src="https://cloud.githubusercontent.com/assets/540990/26134954/2c18dba0-3a80-11e7-9bf7-59e200d92851.png">

Fixed https://github.com/bizbudding/maitheme-engine/commit/91e4365d08ca99f212db7dceeec9ea2a1cb2c5ab
